export const CARD_VALIDATION_INFO = {
  TOTAL_CARD_INPUTS: 4,
  VISA_CARD_START_NUMBER: 4,
  MASTER_CARD_MIN_START_NUMBER: 51,
  MASTER_CARD_MAX_START_NUMBER: 55,
  CARD_MAX_LENGTH: 4,
  EXPIRE_DATE_MAX_LENGTH: 2,
  CVC_MAX_LENGTH: 3,
  PASSWORD_MAX_LENGTH: 2,
  MIN_VALID_MONTH: 1,
  MAX_VALID_MONTH: 12,
  MIN_VALID_YEAR: 25,
};
