const CARD = {
  NICKNAME_MAX_LENGTH: 10,
  SECURITY_CODE_LENGTH: 3,
  SERIAL_NUMBER_LENGTH: 16,
  SERIAL_ID_CODE_LENGTH: 8,
  SERIAL_NUMBER_UNIT_LENGTH: 4,
  EXPIRATION_DATE_LENGTH: 4,
  USER_NAME_MAX_LENGTH: 30,
};

export default CARD;
