export const CARD_INPUT_LIMIT = {
  CARD_NUMBER_MAX_LENGTH: 4,
  CVC_NUMBER_MAX_LENGTH: 3,
  PASSWORD_MAX_LENGTH: 2,
  EXPIRATION_DATE_MAX_LENGTH: 2,
  EXPIRATION_DATE_MIN_MONTH: 1,
  EXPIRATION_DATE_MAX_MONTH: 12,
} as const;
