const CONDITION = {
  VISA: '4',
  MASTER_CARD_MIN: 50,
  MASTER_CARD_MAX: 56,
  TEXT_LENGTH_MIN: 0,
  CARD_NUMBER_LENGTH_MAX: 4,
  DATE_LENGTH_MAX: 2,
  PASSWORD_LENGTH_MAX: 2,
  CVC_LENGTH_MIN: 3,
  CVC_LENGTH_MAX: 4,
} as const;

export default CONDITION;
