export const CARD_ISSUER = {
  bcCard: 'BC카드',
  31: 'BC카드',
  shCard: '신한카드',
  41: '신한카드',
  kakaoCard: '카카오뱅크',
  15: '카카오뱅크',
  hyundaiCard: '현대카드',
  61: '현대카드',
  wooriCard: '우리카드',
  W1: '우리카드',
  lotteCard: '롯데카드',
  71: '롯데카드',
  hanaCard: '하나카드',
  21: '하나카드',
  kbCard: '국민카드',
  11: '국민카드',
} as const;

export const CARD_ISSUER_CODE = {
  bcCard: '31',
  31: 'bcCard',
  shCard: '41',
  41: 'shCard',
  kakaoCard: '15',
  15: 'kakaoCard',
  hyundaiCard: '61',
  61: 'hyundaiCard',
  wooriCard: 'W1',
  W1: 'wooriCard',
  lotteCard: '71',
  71: 'lotteCard',
  hanaCard: '21',
  21: 'hanaCard',
  kbCard: '11',
  11: 'kbCard',
} as const;
