const LOCAL_STORAGE_KEY = "cardList";

const SECURITY_TEXT_ICON = "•";
const DATE_DIVIDER = "/";

const EXPIRATION_DATE_UNIT_LENGTH = 2;
const EXPIRATION_DATE_INPUT_MAX_LENGTH = 5;

const REGEX = {
  ONLY_NUMBER: /^\d*$/,
  NON_NUMBER: /\D/g,
  ENGLISH_AND_WHITESPACE: /^[a-zA-Z ]*$/,
  DATE_FORMAT: /^(?:\d{0,2}\/?\d{0,2})?$/,
  TWO_DIGIT: /(\d{2})/,
  TWO_CHAR_SEQUENCE: /.{1,2}/g,
};

export {
  LOCAL_STORAGE_KEY,
  SECURITY_TEXT_ICON,
  DATE_DIVIDER,
  EXPIRATION_DATE_UNIT_LENGTH,
  EXPIRATION_DATE_INPUT_MAX_LENGTH,
  REGEX,
};
