export const CARD_COMPANIES = [
  { NAME: '포코 카드', COLOR: '#E24141' },
  { NAME: '준 카드', COLOR: '#547CE4' },
  { NAME: '공원 카드', COLOR: '#73BC6D' },
  { NAME: '브랜 카드', COLOR: '#DE59B9' },
  { NAME: '로이드카드', COLOR: '#04C09E' },
  { NAME: '도비 카드', COLOR: '#E76E9A' },
  { NAME: '콜린 카드', COLOR: '#F37D3B' },
  { NAME: '썬 카드', COLOR: '#FBCD58' },
];

export const ACTION_TYPE = {
  SET_CARD_NUMBER: 'SET_CARD_NUMBER',
  SET_CARD_NUMBER_ERROR_MESSAGE: 'SET_CARD_NUMBER_ERROR_MESSAGE',
  SET_CARD_EXPIRATION: 'SET_CARD_EXPIRATION',
  SET_CARD_EXPIRATION_ERROR_MESSAGE: 'SET_CARD_EXPIRATION_ERROR_MESSAGE',
  SET_CARD_OWNER: 'SET_CARD_OWNER',
  SET_CARD_OWNER_ERROR_MESSAGE: 'SET_CARD_OWNER_ERROR_MESSAGE',
  SET_CARD_CVC: 'SET_CARD_CVC',
  SET_CARD_CVC_ERROR_MESSAGE: 'SET_CARD_CVC_ERROR_MESSAGE',
  SET_CARD_PASSWORD: 'SET_CARD_PASSWORD',
  SET_CARD_PASSWORD_ERROR_MESSAGE: 'SET_CARD_PASSWORD_ERROR_MESSAGE',
  SET_CARD_COMPANY_ERROR_MESSAGE: 'SET_CARD_COMPANY_ERROR_MESSAGE',
  SET_MODAL_FLAG: 'SET_MODAL_FLAG',
  SET_COMPANY_INDEX: 'SET_COMPANY_INDEX',
};
