const CARD_NUMBER_UNIT_MAX_LENGTH = 4;
const CARD_NUMBER_MAX_LENGTH = 16;
const CARD_NUMBER_INPUT_MAX_VISIBLE_LENGTH = 10;
const CARD_NUMBER_INPUT_MAX_LENGTH = 19;

const MAX_VALID_EXPIRATION_YEAR = 5;
const EXPIRATION_DATE_UNIT_LENGTH = 2;
const EXPIRATION_DATE_INPUT_MAX_LENGTH = 5;

const OWNER_NAME_MAX_LENGTH = 20;

const SECURITY_CODE_MIN_LENGTH = 3;
const SECURITY_CODE_MAX_LENGTH = 4;

const PASSWORD_UNIT_MAX_LENGTH = 1;

const CARD_NAME_INPUT_MAX_LENGTH = 20;

const PATTERN = {
  CARD_NUMBER: "^d{4} d{4} •{4} •{4}$",
  EXPIRATION_DATE: "^(0[1-9]|1[0-2])/(2[3-8]|[4-9][0-9])$",
  SECURITY_CODE: "^\\d{3,4}$",
  PASSWORD: "^\\d$",
};

export {
  CARD_NUMBER_UNIT_MAX_LENGTH,
  CARD_NUMBER_MAX_LENGTH,
  CARD_NUMBER_INPUT_MAX_VISIBLE_LENGTH,
  CARD_NUMBER_INPUT_MAX_LENGTH,
  MAX_VALID_EXPIRATION_YEAR,
  EXPIRATION_DATE_UNIT_LENGTH,
  EXPIRATION_DATE_INPUT_MAX_LENGTH,
  OWNER_NAME_MAX_LENGTH,
  SECURITY_CODE_MIN_LENGTH,
  SECURITY_CODE_MAX_LENGTH,
  PASSWORD_UNIT_MAX_LENGTH,
  CARD_NAME_INPUT_MAX_LENGTH,
  PATTERN,
};
