export const CARD_INFO: ICardInfo = {
  NUMBER_LENGTH: 16,
  NUMBER_LENGTH_PART: 4,
  VISA_START_NUMBER: 4,
  MASTER_START_NUMBERS: [51, 52, 53, 54, 55],
  CVC_LENGTH: 3,
  EXPIRATION_DATE_LENGTH: 4,
  EXPIRATION_DATE_LENGTH_PART: 2,
  MASKING_STRING: "•",
  EXPIRATION_SPLIT: "/",
  PASSWORD_LENGTH: 2,
};

interface ICardInfo {
  NUMBER_LENGTH: number;
  NUMBER_LENGTH_PART: number;
  VISA_START_NUMBER: number;
  MASTER_START_NUMBERS: number[];
  CVC_LENGTH: number;
  EXPIRATION_DATE_LENGTH: number;
  EXPIRATION_DATE_LENGTH_PART: number;
  MASKING_STRING: string;
  EXPIRATION_SPLIT: string;
  PASSWORD_LENGTH: number;
}
