export const CARD_INPUT = {
  EACH_NUMBER_LENGTH: 4,
  EACH_EXPIRY_DATE_LENGTH: 2,
  CVC_LENGTH: 3,
};

export const NETWORK_BRAND_RULE = {
  VISA_START_NUMBER: "4",
  MASTER_START_NUMBER: "5",
  MASTER_SECOND_NUMBER: ["1", "2", "3", "4", "5"],
};
