const FONT_PRIMARY_COLOR = "#000";
const PRIMARY_BG_COLOR = "#fff";
const HYPHEN_PRIMARY_COLOR = "#8a8a8a";
const LABEL_PRIMARY_COLOR = "#525252";
const INPUT_PRIMARY_BG_COLOR = "#ecebf1";
const PLACEHOLDER_PRIMARY_COLOR = "#a0a0a0";
const ITEM_HOVER_PRIMARY_BG_COLOR = "#d2d2d2";
const DOT_PRIMARY_COLOR = "#04c09e";
const DIMMED_PRIMARY_BG_COLOR = "#00000080";
const BUBBLE_PRIMARY_BG_COLOR = "#ecebf1";
const BUBBLE_PRIMARY_COLOR = "#525252";
const ADD_CARD_ITEM_BG_COLOR = "#e5e5e5";

export {
  FONT_PRIMARY_COLOR,
  PRIMARY_BG_COLOR,
  HYPHEN_PRIMARY_COLOR,
  LABEL_PRIMARY_COLOR,
  INPUT_PRIMARY_BG_COLOR,
  PLACEHOLDER_PRIMARY_COLOR,
  ITEM_HOVER_PRIMARY_BG_COLOR,
  DOT_PRIMARY_COLOR,
  DIMMED_PRIMARY_BG_COLOR,
  BUBBLE_PRIMARY_BG_COLOR,
  BUBBLE_PRIMARY_COLOR,
  ADD_CARD_ITEM_BG_COLOR,
};
