const CONSTANT = {
  NUMBER_INPUT_MAX_LENGTH: 4,
  SECURITY_INPUT_MAX_LENGTH: 3,
  PASSWORD_INPUT_MAX_LENGTH: 1,
  MONTH_INPUT_MAX_LENGTH: 2,
  YEAR_INPUT_MAX_LENGTH: 2,
  OWNER_NAME_MAX_LENGTH: 30,
};

export default CONSTANT;
