export const MAX_NAME_LENGTH = 30;

export const INPUT = {
  MAX_CARD_NUMBER_LENGTH: 16,
  MAX_EXPIRED_PERIOD_LENGTH: 4,
  MIN_NAME_LENGTH: 0,
  MAX_CVC_LENGTH: 3,
  FIRST_PASSWORD: 0,
  SECOND_PASSWORD: 1,
};
