export const MAX_NAME_LENGTH = 30;

export const INPUT = {
  MAX_CARD_NUMBER_PART_LENGTH: 4,
  MAX_EXPIRED_PERIOD_MONTH_LENGTH: 2,
  MAX_EXPIRED_PERIOD_YEAR_LENGTH: 2,
  MIN_NAME_LENGTH: 0,
  MAX_CVC_LENGTH: 3,
  MAX_FIRST_PASSWORD_LENGTH: 1,
  MAX_SECOND_PASSWORD_LENGTH: 1,
};
