export { ReactComponent as BC } from './bc.svg';
export { ReactComponent as HANA } from './hana.svg';
export { ReactComponent as HYUNDAI } from './hyundai.svg';
export { ReactComponent as KAKAOBANK } from './kakaobank.svg';
export { ReactComponent as KUKMIN } from './kukmin.svg';
export { ReactComponent as LOTTE } from './lotte.svg';
export { ReactComponent as SINHAN } from './sinhan.svg';
export { ReactComponent as WOORI } from './woori.svg';
export { ReactComponent as Spinner } from './spinner.svg';
