export enum CARD_COMPANIES {
  BC = 'BC카드',
  SHINHAN = '신한카드',
  KAKAO = '카카오뱅크',
  HYUNDAI = '현대카드',
  WOORI = '우리카드',
  LOTTE = '롯데카드',
  HANA = '하나카드',
  KB = '국민카드',
}

export const CARD_COMPANIES_ARRAY = [
  CARD_COMPANIES.BC,
  CARD_COMPANIES.SHINHAN,
  CARD_COMPANIES.KAKAO,
  CARD_COMPANIES.HYUNDAI,
  CARD_COMPANIES.WOORI,
  CARD_COMPANIES.LOTTE,
  CARD_COMPANIES.HANA,
  CARD_COMPANIES.KB,
];

export const CARD_COMPANIES_COLOR = Object.freeze({
  [CARD_COMPANIES.BC]: '#F04651',
  [CARD_COMPANIES.SHINHAN]: '#0046FF',
  [CARD_COMPANIES.KAKAO]: '#FFE600',
  [CARD_COMPANIES.HYUNDAI]: '#000000',
  [CARD_COMPANIES.WOORI]: '#007BC8',
  [CARD_COMPANIES.LOTTE]: '#ED1C24',
  [CARD_COMPANIES.HANA]: '#009490',
  [CARD_COMPANIES.KB]: '#6A6056',
});

export const CARD_COMPANIES_DEFAULT_COLOR = '#333333';
